### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by xmoroccan**
Minimal tests for the package:

- [x] `make:seo` Command tests
    - [x] Test creating command
    - [x] Test duplicated generators _(I don't know how we can achieve that)_

- [ ] Package should distinct value types
- [ ] Generators render the expected meta
- [ ] Generators render the expected schema

### CODE REVIEW

**Comment by melbahja** [comment]
I didn't understand what do you mean by: "Test duplicated generators"?

**Comment by xmoroccan** [comment]
For the make command, there are three cases:
1. Command create a MetaGenerator successfully
2. MetaGenerator already exists _(What you ask for @melbahja )_
3. name argument not supplied _(Here we should show a nice message as Laravel do, not throwing an exception)_

**Comment by melbahja** [comment]
For duplicated generators you can assert this message in output: `{class} already exists`, {class} is the value of `app_path("Seo/{name}.php")`, and {name} is the argument.

**Comment by xmoroccan** [comment]
Yeep in Laravel application, but in the package, there is no `app_path()` in fact we don't even create the class, we just faking the command, correct me if I'm wrong.

**Pull request merged**
