### PR TITLE
Update style-ci cofnig

### PR DESCRIPTION
**Pull request by xmoroccan**

### CODE REVIEW

**Comment by melbahja** [comment]
Looks good to me.

**Comment by xmoroccan** [comment]
But I have problems with style-ci, I can't see it in my account, I don't know why maybe I'm not admin on this repo, can you please try from your side on the style-ci website, to check the config before the merge.
cc @melbahja

**Comment by melbahja** [comment]
You have to switch from your personal account to Org in style-ci, I'm going to set up it

**Comment by xmoroccan** [comment]
I think now it's ok, we just need to merge the fix from style ci, cc @melbahja

**Pull request merged**
