### PR TITLE
Require `Illuminate\support` instead the full framework

### PR DESCRIPTION
**Pull request by xmoroccan**

### CODE REVIEW

**Comment by melbahja** [comment]
I think we should require `laravel/framework` for testing purposes, like [sitemap](https://github.com/OpenIMW/laravel-sitemap/blob/master/composer.json)

**Comment by xmoroccan** [comment]
Just to minimize the time of building when Github actions run, in fact, in the entire package I don't see any namespaces except `Illuminate/Support` , later if we need something else we'll just require it, for example `Illuminate/Database`, checkout this from laravel-translatable:
https://github.com/Astrotomic/laravel-translatable/blob/889f8b91f28a8a72873099cf452945adbd03dc9f/composer.json#L25-L30

and a quote from the [Laravel docs (Package development)](https://laravel.com/docs/5.8/packages#service-providers)

> A service provider extends the `Illuminate\Support\ServiceProvider` class and contains two methods: register and boot. The base ServiceProvider class is located in the `illuminate/support` Composer package.

from the context  Laravel itself encourage requiring just what you need, that's why there is a read-only repos since a full stack Laravel app contain all these packages.

**Comment by xmoroccan** [comment]
I'm not familiar with composer version constraints, so you can change it, I should educate myself!!

**Comment by melbahja** [comment]
OK bro I have no problem.
Thanks

**Pull request merged**
